version: '3'

services:
#  db:
#    container_name: postgres-db
#    restart: unless-stopped
#    image: postgres:13-alpine3.15
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#
  redis:
    restart: unless-stopped
    image: redis:alpine
    ports:
      - 6379:6379

  web-server:
    container_name: birthday-wish
    restart: unless-stopped
    build: .
    entrypoint: /birthday_wish/server-entrypoint.sh
#    volumes:
#      - .:/birthday_wish
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
    ports:
      - 8000:8000
    depends_on:
      - redis
#      - db

  celery-worker:
    build: .
    entrypoint: /birthday_wish/worker-entrypoint.sh
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
    depends_on:
      - redis

  celery-beat:
    build: .
    entrypoint: /birthday_wish/beat-entrypoint.sh
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
    depends_on:
      - redis

volumes:
    postgres_data: