version: '3'

services:
  db:
    container_name: postgres-db
    restart: unless-stopped
    image: postgres:13-alpine3.15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    restart: unless-stopped
    image: redis:alpine
    ports:
      - 6379:6379

  web-server:
    container_name: birthday-wish
    restart: unless-stopped
    build: .
    entrypoint: /usr/local/bin/server-entrypoint.sh
    volumes:
      - .:/birthday_wish
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
      DATABASE: postgresql
      POSTGRES_HOST: db
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db

  celery-worker:
    restart: unless-stopped
    build: .
    entrypoint: /usr/local/bin/worker-entrypoint.sh
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
      DATABASE: postgresql
      POSTGRES_HOST: db
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - redis

  celery-beat:
    restart: unless-stopped
    build: .
    entrypoint: /usr/local/bin/beat-entrypoint.sh
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
      DATABASE: postgresql
      POSTGRES_HOST: db
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - redis

volumes:
    postgres_data: